# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: 62e55499-1bcc-41c6-928a-1b56ec250d84-capi-aws
rules:
- apiGroups:
  - 'apiextensions.k8s.io'
  resources:
  - customresourcedefinitions
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
