# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 62e55499-1bcc-41c6-928a-1b56ec250d84-capi-aws-check
  namespace: 62e55499-1bcc-41c6-928a-1b56ec250d84
spec:
  template:
    metadata:
      name: 62e55499-1bcc-41c6-928a-1b56ec250d84-capi-aws
    spec:
      serviceAccountName: 62e55499-1bcc-41c6-928a-1b56ec250d84-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 62e55499-1bcc-41c6-928a-1b56ec250d84
        - 62e55499-1bcc-41c6-928a-1b56ec250d84
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 62e55499-1bcc-41c6-928a-1b56ec250d84-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
