# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 62e55499-1bcc-41c6-928a-1b56ec250d84-capi-aws
  namespace: 62e55499-1bcc-41c6-928a-1b56ec250d84
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 62e55499-1bcc-41c6-928a-1b56ec250d84-capi-aws
subjects:
- kind: ServiceAccount
  name: 62e55499-1bcc-41c6-928a-1b56ec250d84-capi-aws
